---
name: 'Build LaTeX Document with Biber'
on:
  push:
    branches:
      - trunk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/cache@v3
        name: Tectonic Cache
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
          restore-keys: |
           ${{ runner.os }}-tectonic-
      - uses: wtfjoke/setup-tectonic@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          biber-version: '2.17'

      - name: Build protocol
        working-directory: .
        run: tectonic -X build

      - name: Upload pdf
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: |
            build/*
